### ISSUE TITLE
Unable to recompile with wider qubit type

### ISSUE THREAD

**Issue by mstf7249** [iic-jku/qcec#7]
HI! Thank you for developing this tool.

I was trying to run benchmarks with more than 128 qubits, and then the following message was shown by the program:

*what():  Requested too many qubits to be handled by the DD package. Qubit datatype only allows up to 128 qubits, while 232 were requested. If you want to use more than 128 qubits, you have to recompile the package with a wider Qubit type in `export/dd_package/include/dd/Definitions.hpp!`*

Thus, I changed the qubit type in **Definitions.hpp** from **std::int_fast8_t** to **std::int_fast16_t** and recompiled the package. However, the compilation was not successful and the following error message was provided:

*qcec/extern/qfr/src/algorithms/Grover.cpp:41:69: error: no matching function for call to ‘max(long unsigned int, int)’
   41 |         auto target = static_cast<dd::Qubit>(std::max(nqubits - 1, 0));*

Using other types does not work either. Am I missing something out? 
Thank you!

**Comment by burgholzer** [comment]
Thanks for reaching out!

Could you try changing the line in the error message (i.e. `qcec/extern/qfr/src/algorithms/Grover.cpp:41:69`) to
```
auto target = static_cast<dd::Qubit>(std::max(static_cast<dd::QubitCount>(nqubits - 1), static_cast<dd::QubitCount>(0)));
```
and see if this resolves the error (or if other errors pop up)?

I am able to compile the code on my machine when changing the qubit type from `std::int_fast8_t` to `std::int_fast16_t` without any problems. This might be because the actual types underlying these `std::int_fastx_t` types are system dependent which might in turn lead to the compiler complaining since it can't find the definition for a certain standard library function (in the case above `std::max`).

**Comment by mstf7249** [comment]
> Thanks for reaching out!
> 
> Could you try changing the line in the error message (i.e. `qcec/extern/qfr/src/algorithms/Grover.cpp:41:69`) to
> 
> ```
> auto target = static_cast<dd::Qubit>(std::max(static_cast<dd::QubitCount>(nqubits - 1), static_cast<dd::QubitCount>(0)));
> ```
> 
> and see if this resolves the error (or if other errors pop up)?
> 
> I am able to compile the code on my machine when changing the qubit type from `std::int_fast8_t` to `std::int_fast16_t` without any problems. This might be because the actual types underlying these `std::int_fastx_t` types are system dependent which might in turn lead to the compiler complaining since it can't find the definition for a certain standard library function (in the case above `std::max`).

This just works!
Thank you for your help!
